### ISSUE TITLE
Errors after update to 1.0.23

### ISSUE THREAD

**Issue by bruxy70** [lendy007/homeassistant-skodaconnect#6]
## Environment

- skodaconnect release with the issue: 1.0.23
- Last working homeassistant-skodaconnect release (if known): 1.0.19
- Home Assistant Core release with the issue:  2020.12.1
- Operating environment (Home Assistant/Supervised/Docker/venv):  Home Assistant
- Car model and year: Citigo eV 2020
- Valid We Connect subscription:  Yes
- Debug logs enabled:  Yes

## Describe the bug

Errors in the log

## Steps to Reproduce

Restart, check logs

## Expected behavior

Not sure if this impact functionality. I was actually checking logs for my own integration I maintain, and I noticed the errors below.

## Traceback/Error logs

```txt
  File "/usr/local/lib/python3.8/site-packages/dashboardskoda.py", line 126, in state
    if val and self.unit and "mi" in self.unit and self.convert == True:
AttributeError: 'Sensor' object has no attribute 'convert'

  File "/usr/local/lib/python3.8/site-packages/dashboardskoda.py", line 134, in state
    elif val and self.unit and "°C" in self.unit and self.convert == True:
AttributeError: 'Sensor' object has no attribute 'convert'

Exception in async_write_ha_state when dispatching 'skodaconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state sstate = self.state File "/config/custom_components/skodaconnect/sensor.py", line 27, in state return self.instrument.state File "/usr/local/lib/python3.8/site-packages/dashboardskoda.py", line 134, in state elif val and self.unit and "°C" in self.unit and self.convert == True: AttributeError: 'Sensor' object has no attribute 'convert'
Exception in async_write_ha_state when dispatching 'skodaconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state sstate = self.state File "/config/custom_components/skodaconnect/sensor.py", line 27, in state return self.instrument.state File "/usr/local/lib/python3.8/site-packages/dashboardskoda.py", line 126, in state if val and self.unit and "mi" in self.unit and self.convert == True: AttributeError: 'Sensor' object has no attribute 'convert'
```

**Comment by Farfar** [comment]
Should be resolved in version 1.0.24

**Comment by bruxy70** [comment]
Thanks
